# Generated by Django 4.2.6 on 2023-10-12 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'категория меню',
                'verbose_name_plural': 'категории меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('url', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_menu', to='app.menucategory', verbose_name='Категория')),
                ('parent', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='parent_menu', to='app.menuitem', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'пункт меню',
                'verbose_name_plural': 'пункты меню',
            },
        ),
    ]
